---
title: "Desafio 3 - ME315"
author: "Bruce Trevisan"
date: "2025-09-01"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Arquivo JSON

# Payment Card Fraud Detection 2025
# Real-time fraud prevention system for luxury retail transactions analysis 2025

# PACOTES NECESSARIOS PARA FAZER UPLOAD
library(arrow)
library(tibble)
library(jsonlite)

# Ler o JSON
json_data <- fromJSON("luxury_cosmetics_fraud_analysis_2025.json")

str(json_data, max.level = 2) #Com esse comando mostra se é lista, matriz ou um dataframe disfarçado.

# Transformar em tibble
json_tbl <- as_tibble(json_data)

# Ver a estrutura
glimpse(json_tbl)

```

```{r}
# Arquivo Parquet

# Serial Killer Data Blog
# Pandas Parquet with the blog posts of a Serial Kerial scrapped

library(arrow)
# Como o arquivo é pequeno não precisa usar SPARK, somente com o Arrow ele funciona perfeitamente 

# Carregar o arquivo Parquet
parquet_tbl <- read_parquet("Serial_KIller.parquet")

# Explorar os dados
glimpse(parquet_tbl)

```

```{r}
#Teste de tempo resposta dataset

bench::mark(
  arrow = read_parquet("Serial_KIller.parquet")
)
```

